apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtmp-server
  labels:
    app: rtmp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtmp
  template:
    metadata:
      labels:
        app: rtmp
    spec:
      containers:
        - name: nginx-rtmp
          image: tiangolo/nginx-rtmp
          ports:
            - containerPort: 1935
          volumeMounts:
            - name: rtmp-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
        - name: rtmp-conf
          configMap:
            name: rtmp-config
            items:
              - key: nginx.conf
                path: nginx.conf

---
apiVersion: v1
kind: Service
metadata:
  name: rtmp-service
spec:
  type: NodePort
  selector:
    app: rtmp
  ports:
    - protocol: TCP
      port: 1935
      targetPort: 1935
      nodePort: 31935
